version: '3'

services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - VCAP_SERVICES=${VCAP_SERVICES}
      - VCAP_APPLICATION=${VCAP_APPLICATION}
      - DISABLE_COLLECTSTATIC=${DISABLE_COLLECTSTATIC}
      - JWT_CERT=${JWT_CERT}
      - JWT_KEY=${JWT_KEY}
      - OIDC_RP_CLIENT_ID=${OIDC_RP_CLIENT_ID}
      - SECRET_KEY=${SECRET_KEY}
    image: web
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/tdpapp
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/tdpapp
    ports:
      - "8001:8001"
